version: '3'
services:
  gin-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_NAME=haven
      - DB_USER=postgres
      - DB_PASSWORD=somesecret
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSLMODE=disable

  postgres:
    image: postgres:latest
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=somesecret
volumes:
  postgres_data:
